services:
  nodejs2022q2-service:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/usr/src/nodejs2022q2-service
      - /usr/src/nodejs2022q2-service/node_modules
    depends_on:
      - postgresql
    networks: 
      - app    
  postgresql:
    container_name: postgres
    build:
      context: .
      dockerfile: ./postgresql/Dockerfile
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_DB: "localhost"
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks: 
      - app
networks:
    app:
        name: app
        driver: bridge
volumes:
  pgdata:
  nodejs2022q2-service: